---
# Change these first
owner: Allaman # Your GitHub username
repo: status # Your GitHub repository name
user-agent: allaman

# Add your sites here
sites:
  - name: mijope.de
    url: https://mijope.de
  - name: rootknecht.net
    url: https://rootknecht.net
    icon: https://rootknecht.net/logo.png
  - name: Syncthing
    url: $SYNC
    expectedStatusCodes:
      - 200
    icon: https://syncthing.net/img/favicons/favicon-32x32.png
  - name: Timetrack
    url: $TRACK
    icon: https://www.timetrackapp.com/wp-content/uploads/2020/04/favicon.png
  - name: Git
    url: $GIT
    icon: https://forgejo.org/favicon.svg
  - name: RSS
    url: $RSS
    icon: https://rss.com/blog/wp-content/uploads/2019/10/logo_RSS_square_500x500-150x150.png
  - name: Cloud
    url: $Cloud
  - name: Library
    url: $LIBRARY

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status of my systems"
  navbar:
    - title: Status
      href: /
    - title: Source code
      href: https://github.com/$OWNER/$REPO
    - title: Me
      href: https://github.com/$OWNER/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
