# Change these first
owner: Allaman # Your GitHub username
repo: status # Your GitHub repository name
user-agent: allaman

# Add your sites here
sites:
  - name: mjp
    url: https://mijope.de
  - name: knowledge
    url: https://knowledge.rootknecht.net
    icon: https://knowledge.rootknecht.net/user/themes/mytheme/images/logo.png
  - name: Syncthing
    url: $SYNC
    expectedStatusCodes:
      - 401
    icon: https://syncthing.net/img/favicons/favicon-32x32.png
  - name: Timetrack
    url: $TRACK
    icon: https://www.timetrackapp.com/wp-content/uploads/2020/04/favicon.png
  - name: Huginn
    url: $HUGINN
    icon: https://raw.githubusercontent.com/huginn/huginn/master/media/huginn-icon-64.png
  - name: Git
    url: $GIT
    icon: https://gitea.io/images/favicon.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
